### PR TITLE
Feat/wizard wrapper

### LINKED ISSUE #51: Framer-motion not working exit animation
In examples, you can't find animation with on exit when I try to add, is not working. 
I checked with framer docs and looks ok but when react unmount step didn't animate.

### PR DESCRIPTION
**Pull request by devrnt**
Add `wrapper` prop to `<Wizard />`, it's an optional wrapper that is exclusively wrapped around the active step component. It is not wrapped around the `header` and `footer`

~~⚠️ TODO: update documentation~~ done

Fixes #51

### CODE REVIEW

**Comment by HPieters** [comment]
Solution works for me with framer-motion, need help with the docs?

**Comment by devrnt** [comment]
PRs are always welcome, thanks in advance!

**Comment by Luc9802** [comment]
Hi @devrnt, are there any news on the release of this feature?
Thanks in advance

**Comment by devrnt** [comment]
I was waiting for people to need this feature and apparently, this is clearly the case.

I'll try to ship this feature soon

**Comment by devrnt** [comment]
Closes https://github.com/devrnt/react-use-wizard/issues/51 and https://github.com/devrnt/react-use-wizard/issues/118

**Pull request merged**
