### PR TITLE
feat: check handle step.

### PR DESCRIPTION
**Pull request by matand-dd**
Make it possible to interrupt the handleStep to navigate to next step.

### CODE REVIEW

**Comment by Luc9802** [comment]
Is there a release date also for this by chance?
Thanks

**Comment by justsaul** [comment]
Are there any plans to support such functionality?  @devrnt

**Comment by devrnt** [comment]
> 1. Throwing error within handler just for the sake of stopping nextStep() feels counter intuitive.

Indeed, this feels a bit off at the moment 

> 2. Actual handling of such error that has been thrown from handleStep() is not documented at all. Yes, it is easy to make the connection between handleStep() and nextStep(), however, it would help a lot if it were to be documented.

You're right, there is only one mention in the docs at the moment, are you willing to pick this up?

**Comment by algooru** [comment]
> You're right, there is only one mention in the docs at the moment, are you willing to pick this up?

I am willing to pick this up.

**Comment by xucongli1989** [comment]
I am also looking at this feature.

**Comment by giacomocerquone** [comment]
I've noticed this pr only after leaving the following comment (which is weirdly not linked): https://github.com/devrnt/react-use-wizard/issues/74#issuecomment-1731210574

I gotta say that throwing is perfectly fine, it just needs a mention on the docs.

**Comment by devrnt** [comment]
Closing because [already possible](https://github.com/devrnt/react-use-wizard/pull/79#issuecomment-952305681) with the current API

**Pull request closed without merging**
